const COUNTRY_NAMES: Record<string, string> = {
	af: "afghanistan",
	al: "albania",
	dz: "algeria",
	ar: "argentina",
	am: "armenia",
	au: "australia",
	at: "austria",
	az: "azerbaijan",
	bd: "bangladesh",
	by: "belarus",
	be: "belgium",
	bo: "bolivia",
	br: "brazil",
	bg: "bulgaria",
	ca: "canada",
	cl: "chile",
	cn: "china",
	co: "colombia",
	cr: "costa rica",
	hr: "croatia",
	cu: "cuba",
	cy: "cyprus",
	cz: "czechia",
	dk: "denmark",
	ec: "ecuador",
	eg: "egypt",
	sv: "el salvador",
	ee: "estonia",
	et: "ethiopia",
	fi: "finland",
	fr: "france",
	ge: "georgia",
	de: "germany",
	gh: "ghana",
	gr: "greece",
	gt: "guatemala",
	hn: "honduras",
	hk: "hong kong",
	hu: "hungary",
	is: "iceland",
	in: "india",
	id: "indonesia",
	ir: "iran",
	iq: "iraq",
	ie: "ireland",
	il: "israel",
	it: "italy",
	ci: "ivory coast",
	jm: "jamaica",
	jp: "japan",
	jo: "jordan",
	kz: "kazakhstan",
	ke: "kenya",
	kw: "kuwait",
	kg: "kyrgyzstan",
	lv: "latvia",
	lb: "lebanon",
	lt: "lithuania",
	lu: "luxembourg",
	my: "malaysia",
	mv: "maldives",
	mx: "mexico",
	md: "moldova",
	mn: "mongolia",
	ma: "morocco",
	mm: "myanmar",
	np: "nepal",
	nl: "netherlands",
	nz: "new zealand",
	ni: "nicaragua",
	ng: "nigeria",
	no: "norway",
	om: "oman",
	pk: "pakistan",
	pa: "panama",
	py: "paraguay",
	pe: "peru",
	ph: "philippines",
	pl: "poland",
	pt: "portugal",
	qa: "qatar",
	ro: "romania",
	ru: "russia",
	sa: "saudi arabia",
	rs: "serbia",
	sg: "singapore",
	sk: "slovakia",
	si: "slovenia",
	za: "south africa",
	kr: "south korea",
	es: "spain",
	lk: "sri lanka",
	se: "sweden",
	ch: "switzerland",
	tw: "taiwan",
	tz: "tanzania",
	th: "thailand",
	tn: "tunisia",
	tr: "turkey",
	ua: "ukraine",
	ae: "united arab emirates",
	gb: "united kingdom",
	us: "united states",
	uy: "uruguay",
	uz: "uzbekistan",
	ve: "venezuela",
	vn: "vietnam",
	fj: "fiji",
	gu: "guam",
	nc: "new caledonia",
};

export function getCountryName(code: string): string {
	return COUNTRY_NAMES[code] || "";
}
